overblog_graphql:
    definitions:
        schema:
            query: Query
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql"
                    suffix: ~
        builders:
            field:
                alias:
                    resolver: 'Overblog\GraphQLBundle\Definition\Builder\MappingInterface::BUILDER_RESOLVE'
