controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

graphql_endpoint:
    path: /graphql
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction

graphql_explorer:
    path: /graphiql
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::graphiQLAction
